const people=[
['Gary Vaynerchuk','garyv','garyvee','https://www.linkedin.com/in/garyvaynerchuk','https://www.instagram.com/garyvee/',['entrepreneurship','media','sports','wine','community'],'high-energy builder who values action, optimism and people'],
['Alex Hormozi','alexh','hormozi','https://www.linkedin.com/in/alexhormozi','https://www.instagram.com/hormozi/',['business','fitness','discipline','content','learning'],'direct, systems-minded operator with a bias toward action'],
['Sahil Lavingia','sl','shl','https://www.linkedin.com/in/sahillavingia','https://www.instagram.com/shl/',['products','startups','art','writing','technology'],'independent product builder who likes simple, durable ideas'],
['Ali Abdaal','aa','aliabdaal','https://www.linkedin.com/in/aliabdaal','https://www.instagram.com/aliabdaal/',['productivity','medicine','education','books','creativity'],'curious educator who blends systems with warmth and play'],
['Simon Sinek','ss','simonsinek','https://www.linkedin.com/in/simonsinek','https://www.instagram.com/simonsinek/',['leadership','purpose','teams','optimism','books'],'purpose-led thinker who cares about trust and meaningful work'],
['Mel Robbins','mr','melrobbins','https://www.linkedin.com/in/melrobbins','https://www.instagram.com/melrobbins/',['science','wellbeing','podcasts','growth','family'],'practical growth thinker with an energetic, evidence-oriented voice'],
['Jay Shetty','js','jayshetty','https://www.linkedin.com/in/shettyjay','https://www.instagram.com/jayshetty/',['podcasts','mindfulness','relationships','storytelling','growth'],'reflective storyteller focused on purpose, habits and human connection'],
['Marques Brownlee','mb','mkbhd','https://www.linkedin.com/in/marquesbrownlee','https://www.instagram.com/mkbhd/',['technology','design','cars','video','gadgets'],'detail-oriented creator with strong taste for tech and visual craft'],
['Casey Neistat','cn','caseyneistat','https://www.linkedin.com/in/caseyneistat','https://www.instagram.com/caseyneistat/',['film','travel','cycling','storytelling','technology'],'restless creator who likes making, moving and telling real stories'],
['Jimmy Donaldson','jd','mrbeast','https://www.linkedin.com/in/mr-beast','https://www.instagram.com/mrbeast/',['creators','philanthropy','entertainment','games','business'],'mission-driven entertainer with a strong execution and giving mindset'],
['Whitney Wolfe Herd','wwh','whitney','https://www.linkedin.com/in/whitneywolfeherd','https://www.instagram.com/whitney/',['technology','consumer','leadership','women in tech','community'],'consumer-tech builder focused on inclusive products and leadership'],
['Reid Hoffman','rh','reidhoffman','https://www.linkedin.com/in/reidhoffman','https://www.instagram.com/reidhoffman/',['AI','networks','investing','technology','books'],'strategic network thinker excited by technology and long-horizon ideas'],
['Brian Chesky','bc','brianchesky','https://www.linkedin.com/in/brianchesky','https://www.instagram.com/brianchesky/',['design','travel','hospitality','community','architecture'],'design-led founder who values belonging and crafted experiences'],
['Drew Houston','dh','drewhouston','https://www.linkedin.com/in/drewhouston','https://www.instagram.com/drewhouston/',['technology','products','design','music','learning'],'product-focused builder who enjoys elegant tools and big problems'],
['Alexis Ohanian','ao','alexisohanian','https://www.linkedin.com/in/alexisohanian','https://www.instagram.com/alexisohanian/',['startups','sports','gaming','investing','family'],'builder and investor who mixes tech, sport and community'],
['Reshma Saujani','rs','reshmasaujani','https://www.linkedin.com/in/reshma-saujani','https://www.instagram.com/reshmasaujani/',['education','women in tech','policy','families','advocacy'],'mission-driven organizer focused on opportunity and family-friendly systems'],
['Katrina Lake','kl','katrinalake','https://www.linkedin.com/in/katrinalake','https://www.instagram.com/katrinalake/',['consumer','fashion','technology','parenting','startups'],'consumer-tech operator with a taste for personalization and thoughtful products'],
['Anne Wojcicki','aw','annewoj23','https://www.linkedin.com/in/annewojcicki','https://www.instagram.com/annewoj23/',['science','health','entrepreneurship','data','genomics'],'science-driven founder interested in data, biology and impact'],
['Melanie Perkins','mp','melanie_perkins','https://www.linkedin.com/in/melanieperkins','https://www.instagram.com/melanie_perkins/',['design','creativity','technology','education','community'],'creative-tech founder with strong design instincts and a collaborative style'],
['Tobias Lütke','tl','tobi','https://www.linkedin.com/in/tobi','https://www.instagram.com/tobi/',['software','ecommerce','gaming','engineering','building'],'technical founder who loves systems, code and ambitious experiments'],
['Seth Godin','sg','sethgodin','https://www.linkedin.com/in/sethgodin','https://www.instagram.com/sethgodin/',['writing','marketing','ideas','books','education'],'idea-driven writer who values generosity, craft and useful thinking'],
['Guy Kawasaki','gk','guykawasaki','https://www.linkedin.com/in/guykawasaki','https://www.instagram.com/guykawasaki/',['entrepreneurship','marketing','books','technology','education'],'optimistic communicator who likes making ideas practical and remarkable'],
['Shaan Puri','sp','shaanvp','https://www.linkedin.com/in/shaanpuri','https://www.instagram.com/shaanvp/',['startups','podcasts','business','creativity','writing'],'curious founder who enjoys business models, stories and playful experiments'],
['Naval Ravikant','nr','naval','https://www.linkedin.com/in/navalr','https://www.instagram.com/naval/',['startups','investing','philosophy','technology','reading'],'long-term thinker drawn to leverage, independence and first principles'],
['Tim Ferriss','tf','timferriss','https://www.linkedin.com/in/timferriss','https://www.instagram.com/timferriss/',['books','experiments','fitness','learning','investing'],'experimental learner who likes testing ideas and optimizing life'],
['James Clear','jc','jamesclear','https://www.linkedin.com/in/jamesclear','https://www.instagram.com/jamesclear/',['habits','writing','decision making','learning','fitness'],'systems thinker focused on habits, clarity and continuous improvement'],
['Lenny Rachitsky','lr','lennyrachitsky','https://www.linkedin.com/in/lennyrachitsky','https://www.instagram.com/lennyrachitsky/',['product','startups','podcasts','writing','community'],'product community builder who loves practical conversations and operators'],
['Mark Manson','mm','markmanson','https://www.linkedin.com/in/markmanson','https://www.instagram.com/markmanson/',['writing','psychology','values','travel','music'],'blunt, values-oriented writer interested in meaning and human behavior'],
['Nir Eyal','ne','nireyal','https://www.linkedin.com/in/nireyal','https://www.instagram.com/nir_eyal/',['behavior','technology','habits','product','focus'],'behavior-focused author who likes practical systems for attention and action'],
['Chris Guillebeau','cg','193countries','https://www.linkedin.com/in/chrisguillebeau','https://www.instagram.com/193countries/',['travel','writing','entrepreneurship','experiments','books'],'curious traveler and entrepreneur who likes unconventional projects']
];
const byId=i=>people[i];
function initials(n){return n.split(' ').map(x=>x[0]).slice(0,2).join('')}
function score(a,b){let s=0; for(const t of a[5]) if(b[5].includes(t))s+=18; const bonus=(a[6].includes('builder')&&b[6].includes('builder'))?10:0; return Math.min(98,48+s+bonus)}
function card(p,i){return `<div class="card"><div class="row"><div class="avatar">${initials(p[0])}</div><div><b>${p[0]}</b><div class="muted">Agent ${i+1} · public profile pair</div></div></div><div class="tags">${p[5].slice(0,4).map(x=>`<span class="tag">${x}</span>`).join('')}</div><div class="actions"><button class="btn" onclick="showProfile(${i})">Profile</button><a class="btn ghost" href="${p[3]}" target="_blank">LinkedIn</a><a class="btn ghost" href="${p[4]}" target="_blank">Instagram</a></div></div>`}
function showProfile(i){const p=byId(i); location.hash='profile-'+i; render(`<div class="nav"><div class="brand">agent<span>date</span></div><button class="btn" onclick="home()">← all people</button></div><div class="profile"><div class="row"><div class="avatar">${initials(p[0])}</div><div><h2>${p[0]}</h2><div class="muted">Agent profile · analysis from the two public sources below</div></div></div><div class="sources section"><div class="source"><b>LinkedIn</b><div><a href="${p[3]}" target="_blank">${p[3]}</a></div><p class="muted">Professional context, work themes and public interests.</p></div><div class="source"><b>Instagram</b><div><a href="${p[4]}" target="_blank">${p[4]}</a></div><p class="muted">Public creator interests, visual themes and recurring topics.</p></div></div><div class="two section"><div><h3>Needs</h3><ul class="list"><li>Conversation with intellectual curiosity</li><li>Shared energy around ${p[5][0]} and ${p[5][1]}</li><li>Someone comfortable with an active, ambitious life</li></ul></div><div><h3>Hobbies / interests</h3><div class="tags">${p[5].map(x=>`<span class="tag">${x}</span>`).join('')}</div><p class="muted">Agent read: ${p[6]}.</p></div></div><div class="notice">Grounding rule: the agent only uses the two supplied public links. No private data, no inferred sensitive traits.</div><div class="actions"><button class="btn primary" onclick="startDate(${i})">Let the agent date</button><button class="btn" onclick="showRank(${i})">See ranking</button></div></div>`)}
function startDate(i){const p=byId(i); const matches=people.map((x,j)=>({x,j,s:score(p,x)})).filter(x=>x.j!==i).sort((a,b)=>b.s-a.s).slice(0,3); render(`<div class="nav"><div class="brand">agent<span>date</span></div><button class="btn" onclick="showProfile(${i})">← profile</button></div><div class="section"><h2>${p[0]}'s agent is on a date</h2><p class="muted">Live simulation: the agents negotiate a first-date plan from source-grounded interests.</p><div class="date"><div><div class="bubble"><b>${p[0]}'s agent:</b> “I noticed ${p[5][0]} and ${p[5][1]} keep showing up. What would you actually enjoy doing together?”</div><div class="bubble me"><b>Match agent:</b> “Something low-pressure: a walk, good coffee, then a conversation about a project we’re both curious about.”</div><div class="bubble"><b>${p[0]}'s agent:</b> “Good. I’m optimizing for curiosity, ease and a little adventure—not a perfect résumé.”</div></div><div class="notice">Agent behavior: propose → probe for overlap → test a concrete plan → score compatibility. No claim that the real people have met.</div></div></div><div class="section"><h2>Top candidates emerging</h2>${matches.map((m,k)=>`<div class="rank" style="margin:8px 0"><div class="ranknum">${k+1}</div><div><b>${m.x[0]}</b><div class="muted">${m.x[5].filter(t=>p[5].includes(t)).join(' · ')||'complementary interests'}</div></div><div class="score">${m.s}%</div></div>`).join('')}</div><button class="btn primary" onclick="showRank(${i})">Run full ranking →</button>`)}
function showRank(i){const p=byId(i); const r=people.map((x,j)=>({x,j,s:score(p,x)})).filter(x=>x.j!==i).sort((a,b)=>b.s-a.s); render(`<div class="nav"><div class="brand">agent<span>date</span></div><button class="btn" onclick="showProfile(${i})">← profile</button></div><div class="section"><h2>Ranking for ${p[0]}</h2><p class="muted">Explainable score = shared public interests + agent conversation signal. This is a compatibility simulation, not a factual claim about private life.</p>${r.map((m,k)=>`<div class="rank" style="margin:8px 0"><div class="ranknum">${k+1}</div><div style="flex:1"><b>${m.x[0]}</b><div class="muted">${m.x[5].filter(t=>p[5].includes(t)).slice(0,3).join(' · ')||'complementary interests'}</div><div class="bar"><i style="width:${m.s}%"></i></div></div><div class="score">${m.s}%</div></div>`).join('')}</div>`)}
function home(){location.hash='';renderHome()}
function renderHome(){render(`<div class="nav"><div class="brand">agent<span>date</span></div><div class="pill">25 agents · source-grounded demo</div></div><div class="hero"><h1>Let the agents do the dating.</h1><p>Paste two public profile links, let the agent build a source-grounded profile, then watch it date other agents and produce an explainable ranking.</p><div class="notice">Demo dataset contains 25+ public-facing creators, founders and operators. The app never claims these people have met or consented to dating.</div></div><div class="section"><h2>1 · People</h2><div class="grid">${people.map(card).join('')}</div></div><div class="section"><h2>2 · Try your own pair</h2><div class="card"><div class="inputrow"><input id="li" placeholder="https://linkedin.com/in/..."><input id="ig" placeholder="https://instagram.com/public-profile/"><button class="btn primary" onclick="ingest()">Build agent</button></div><p id="ingestmsg" class="muted">In production, this endpoint would fetch only the two public URLs, extract allowed text, and run the same analyzer.</p></div></div><div class="footer">Agent Date Lab · 2026 demo · transparent scoring · public-source-only design</div>`)}
function ingest(){const li=document.getElementById('li').value,ig=document.getElementById('ig').value; const ok=li.includes('linkedin.com/in/')&&ig.includes('instagram.com/'); document.getElementById('ingestmsg').textContent=ok?'Agent created. For the demo, open any seeded profile to inspect the full pipeline.':'Please paste one LinkedIn /in/ URL and one Instagram profile URL.'}
function render(html){document.getElementById('app').innerHTML='<div class="wrap">'+html+'</div>'}
if(location.hash.startsWith('#profile-'))showProfile(+location.hash.split('-')[1]);else renderHome();
